- name: Import NodeJS Common Role
  ansible.builtin.include_role:
    name: common
    tasks_from: java

- name: Install Mysql
  ansible.builtin.dnf:
    name:
    - mysql
    - python3-mysqlclient
    state: installed

- name: Load Schema
  community.mysql.mysql_db:
    state: import
    name: all
    target: /app/db/{{ item }}.sql
    login_host: mysql-dev.azdevops.shop
    login_user: root
    login_password: RoboShop@1
  loop:
    - schema
    - app-user
    - master-data

#- name: Load App User
#  community.mysql.mysql_db:
#    state: import
#    name: all
#    target: /app/db/app-user.sql
#    login_host: mysql-dev.azdevops.shop
#    login_user: root
#    login_password: RoboShop@1
#
#- name: Load Master Data
#  community.mysql.mysql_db:
#    state: import
#    name: all
#    target: /app/db/master-data.sql
#    login_host: mysql-dev.azdevops.shop
#    login_user: root
#    login_password: RoboShop@1

