- name: Import NodeJS Common Role
  ansible.builtin.include_role:
    name: common
    tasks_from: nodejs

- name:  Copy MongoDB repo file
  ansible.builtin.template:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install Mongo client
  ansible.builtin.dnf:
    name: mongodb-mongosh
    state: installed

#- name: Load Master Data
#  community.mongodb.mongodb_shell:
#    login_host: mongodb-{{ ENV }}.azdevops.shop
#    file: /app/db/master-data.js
#    idempotent: yes

- name: Execute MongoDB script with shell as root
  ansible.builtin.shell: mongosh --host mongodb-{{ ENV }}.azdevops.shop </app/db/master-data.js
  become: yes
  register: Mongo_Script_output

- name: Status MongoDB
  ansible.builtin.debug:
    msg: "{{ Mongo_Script_output }}"
