- name: Import NodeJS Common Role
  ansible.builtin.include_role:
    name: common
    tasks_from: nodejs

- name:  Copy MongoDB repo file
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install Mongo client
  ansible.builtin.dnf:
    name: mongodb-mongosh
    state: installed

#- name: Load Master Data
#  community.mongodb.mongodb_shell:
#    login_host: mongodb-dev.azdevops.shop
#    file: /app/db/master-data.js
#    idempotent: yes

- name: Execute MongoDB script with shell as root
  ansible.builtin.shell: mongosh --host MONGODB-SERVER-IPADDRESS </app/db/master-data.js
  become: yes
