- name: Setup SystemD service file
  ansible.builtin.template:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service

- name: Start Application
  ansible.builtin.systemd_service:
    name: "{{ app_name }}"
    state: restarted
    enabled: true
    daemon_reload: true